project:
  type: website
  output-dir: docs
  execute-dir: project

bibliography:
  - assets/bib/book.bib
  - assets/bib/packages-r.bib
  - assets/bib/packages-python.bib
biblio-style: apalike
link-citations: true
links-as-notes: true

execute:
  freeze: auto
  eval: true
  echo: true
  warning: true
  message: false
  cache: true

format:
  html:
    theme:
      light: [cosmo, assets/scss/theme-light.scss]
    css: assets/css/global.css
    toc: true
    section-divs: true
    number-sections: false
    embed-resources: false
    anchor-sections: true
    smooth-scroll: true
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.tidy-finance\.org'
    citations-hover: true
    footnotes-hover: true
    code-link: false
    fig-align: "center"
    fig-width: 7
    fig-height: 5
    fig-dpi: 300
    lightbox: auto
    include-after-body:
      - assets/html/footer.html

website:
  title: "Tidy Finance"
  llms-txt: true
  site-url: https://blog.tidy-finance.org
  image: assets/img/cover.png
  repo-url: https://github.com/tidy-finance/blog
  repo-actions: source
  description: "An opinionated approach on empirical research in financial economics"
  favicon: assets/img/favicon.png
  open-graph: true
  page-navigation: true
  bread-crumbs: false
  google-analytics:
    tracking-id: "G-DH3KZSMJ5W"
    anonymze-ip: true
  cookie-consent:
    type: express
    style: interstitial
    palette: light
  navbar:
    logo: assets/img/logo-website-white.png
    pinned: false
    left:
      - href: https://www.tidy-finance.org/chapters/index.qmd
        text: Chapters
      - href: index.qmd
        text: Blog
      - href: https://www.tidy-finance.org/support.html
        text: Support
      - href: https://talks.tidy-finance.org
        text: Talks
      - href: https://www.tidy-finance.org/workshops/reproducible-research-workflows.qmd
        text: Workshops
      
editor: source
